//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matmaxx.Butchr.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSourceFolder {
            get {
                return ((string)(this["LastSourceFolder"]));
            }
            set {
                this["LastSourceFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastTargetFolder {
            get {
                return ((string)(this["LastTargetFolder"]));
            }
            set {
                this["LastTargetFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point SelectorFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["SelectorFormLocation"]));
            }
            set {
                this["SelectorFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 800")]
        public global::System.Drawing.Size SelectorFormSize {
            get {
                return ((global::System.Drawing.Size)(this["SelectorFormSize"]));
            }
            set {
                this["SelectorFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RAW")]
        public string LastRawFormat {
            get {
                return ((string)(this["LastRawFormat"]));
            }
            set {
                this["LastRawFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Programme\\PhotomatixPro3\\PhotomatixCL.exe")]
        public string PhotomatixCommandlinePath {
            get {
                return ((string)(this["PhotomatixCommandlinePath"]));
            }
            set {
                this["PhotomatixCommandlinePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default.xmp")]
        public string DefaultXmpFile {
            get {
                return ((string)(this["DefaultXmpFile"]));
            }
            set {
                this["DefaultXmpFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastXmpImportFile {
            get {
                return ((string)(this["LastXmpImportFile"]));
            }
            set {
                this["LastXmpImportFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastXmpExportFile {
            get {
                return ((string)(this["LastXmpExportFile"]));
            }
            set {
                this["LastXmpExportFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Programme\\PhotomatixPro3\\PhotomatixCL.exe")]
        public string PhotomatixCommandlinePathDefault {
            get {
                return ((string)(this["PhotomatixCommandlinePathDefault"]));
            }
            set {
                this["PhotomatixCommandlinePathDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhotomatixCommandlineOptions {
            get {
                return ((string)(this["PhotomatixCommandlineOptions"]));
            }
            set {
                this["PhotomatixCommandlineOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3 -t1 -s jpg -j 100 -h \"remove\"")]
        public string PhotomatixCommandlineOptionsDefault {
            get {
                return ((string)(this["PhotomatixCommandlineOptionsDefault"]));
            }
            set {
                this["PhotomatixCommandlineOptionsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help\\PhotomatixCommandline.html")]
        public string PhotomatixCommandlineOptionsURL {
            get {
                return ((string)(this["PhotomatixCommandlineOptionsURL"]));
            }
            set {
                this["PhotomatixCommandlineOptionsURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("scratch")]
        public string ScratchDirectoryName {
            get {
                return ((string)(this["ScratchDirectoryName"]));
            }
            set {
                this["ScratchDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteSourceJpgsAfterScratching {
            get {
                return ((bool)(this["DeleteSourceJpgsAfterScratching"]));
            }
            set {
                this["DeleteSourceJpgsAfterScratching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys KeyGroupSelectedImages {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyGroupSelectedImages"]));
            }
            set {
                this["KeyGroupSelectedImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys KeyUngroupSelectedImages {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyUngroupSelectedImages"]));
            }
            set {
                this["KeyUngroupSelectedImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MoveFilesOnImport {
            get {
                return ((bool)(this["MoveFilesOnImport"]));
            }
            set {
                this["MoveFilesOnImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MoveFilesOnDistribute {
            get {
                return ((bool)(this["MoveFilesOnDistribute"]));
            }
            set {
                this["MoveFilesOnDistribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ThumbboxSizeMin {
            get {
                return ((int)(this["ThumbboxSizeMin"]));
            }
            set {
                this["ThumbboxSizeMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int ThumbboxSizeMax {
            get {
                return ((int)(this["ThumbboxSizeMax"]));
            }
            set {
                this["ThumbboxSizeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ThumbboxSizeUsed {
            get {
                return ((int)(this["ThumbboxSizeUsed"]));
            }
            set {
                this["ThumbboxSizeUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ThumbboxMargin {
            get {
                return ((int)(this["ThumbboxMargin"]));
            }
            set {
                this["ThumbboxMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ThumbsizeInterval {
            get {
                return ((int)(this["ThumbsizeInterval"]));
            }
            set {
                this["ThumbsizeInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144")]
        public int SplitVerticalDistance {
            get {
                return ((int)(this["SplitVerticalDistance"]));
            }
            set {
                this["SplitVerticalDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("393")]
        public int SplitHorizontalDistance {
            get {
                return ((int)(this["SplitHorizontalDistance"]));
            }
            set {
                this["SplitHorizontalDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TargetFolderMatchesSourceFolder {
            get {
                return ((bool)(this["TargetFolderMatchesSourceFolder"]));
            }
            set {
                this["TargetFolderMatchesSourceFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AutogroupMinimumInterval {
            get {
                return ((int)(this["AutogroupMinimumInterval"]));
            }
            set {
                this["AutogroupMinimumInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelpImport {
            get {
                return ((bool)(this["ShowHelpImport"]));
            }
            set {
                this["ShowHelpImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelpAutoGroup {
            get {
                return ((bool)(this["ShowHelpAutoGroup"]));
            }
            set {
                this["ShowHelpAutoGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelpDistribute {
            get {
                return ((bool)(this["ShowHelpDistribute"]));
            }
            set {
                this["ShowHelpDistribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelpScratchBatch {
            get {
                return ((bool)(this["ShowHelpScratchBatch"]));
            }
            set {
                this["ShowHelpScratchBatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelpOpenApplication {
            get {
                return ((bool)(this["ShowHelpOpenApplication"]));
            }
            set {
                this["ShowHelpOpenApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelpGroupFiles {
            get {
                return ((bool)(this["ShowHelpGroupFiles"]));
            }
            set {
                this["ShowHelpGroupFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}\\publish\\Catalog.xml")]
        public string PublishSessionCatalogPath {
            get {
                return ((string)(this["PublishSessionCatalogPath"]));
            }
            set {
                this["PublishSessionCatalogPath"] = value;
            }
        }
    }
}
